version: '3.7'

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"

  oauth-helper:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src
        target: /usr/local/src
        consistency: consistent
    logging:
      driver: json-file
    command: ["auth"]