
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'pypkg_README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='oauth_client',
    version='0.2.0',
    python_requires='==3.*,>=3.7.0',
    project_urls={"repository": "https://github.com/dedfriedly-inspirdev/oauth-client-helper"},
    author='Dedric Friedly',
    author_email='dedric.friedly@inspiredev-llc.com',
    license='Apache-2.0',
    keywords='OAuth2 Helper Flask OAuth Redirector',
    classifiers=['Programming Language :: Python :: 3', 'License :: OSI Approved :: Apache License 2.0', 'Operating System :: OS Independent'],
    packages=['build.lib.oauth_client', 'build.lib.oauth_client.config', 'build.lib.oauth_client.objects', 'oauth_client', 'oauth_client.build.lib.config', 'oauth_client.build.lib.objects', 'oauth_client.config', 'oauth_client.objects'],
    package_dir={"": "src"},
    package_data={"oauth_client": ["dist/*.gz", "dist/*.whl", "oauth_client.egg-info/*.txt", "oauth_client_helper.egg-info/*.txt", "templates/*.j2"]},
    install_requires=['dynaconf[all]==2.*,>=2.2.3', 'filelock==3.*,>=3.0.12', 'flask==1.*,>=1.1.2', 'flask-bootstrap4==4.*,>=4.0.2', 'flask-talisman==0.*,>=0.7.0', 'flask-wtf==0.*,>=0.14.3', 'pandas==1.*,>=1.0.3', 'pyopenssl==19.*,>=19.1.0', 'redis==3.*,>=3.4.1', 'requests==2.*,>=2.23.0'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "ipython==7.*,>=7.13.0"]},
)
